"""add user

Revision ID: 3dbe74428e3b
Revises: b8b7ee1d49d6
Create Date: 2023-10-17 02:06:31.110185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dbe74428e3b'
down_revision: Union[str, None] = 'b8b7ee1d49d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('accounts_username_fkey', 'accounts', type_='foreignkey')
    op.create_foreign_key(None, 'accounts', 'users', ['username'], ['username'], ondelete='CASCADE')
    op.drop_constraint('comment_images_user_id_fkey', 'comment_images', type_='foreignkey')
    op.drop_column('comment_images', 'user_id')
    op.add_column('comments', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'comments', 'users', ['user_id'], ['id'])
    op.add_column('images', sa.Column('public_id', sa.String(length=255), nullable=False))
    op.add_column('images', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('images', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('images', 'rating',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    op.add_column('ratings', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('access_token', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'access_token')
    op.drop_column('ratings', 'created_at')
    op.alter_column('images', 'rating',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.drop_column('images', 'updated_at')
    op.drop_column('images', 'created_at')
    op.drop_column('images', 'public_id')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'user_id')
    op.add_column('comment_images', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('comment_images_user_id_fkey', 'comment_images', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'accounts', type_='foreignkey')
    op.create_foreign_key('accounts_username_fkey', 'accounts', 'users', ['username'], ['username'])
    # ### end Alembic commands ###
