"""change type of rate

Revision ID: b8b7ee1d49d6
Revises: 07ace60adfe1
Create Date: 2023-10-13 22:37:23.944942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8b7ee1d49d6'
down_revision: Union[str, None] = '07ace60adfe1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', 'rating',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    op.alter_column('ratings', 'rate',
               existing_type=sa.REAL(),
               type_=sa.Integer(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ratings', 'rate',
               existing_type=sa.Integer(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('images', 'rating',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    # ### end Alembic commands ###
